server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://115.159.101.70:3306/bysjgl?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lz645489
  thymeleaf:
    prefix:
         classpath: /templates/
  #静态资源访问路径：用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
  mvc:
    static-path-pattern: /static/**
  #上传文件使用
  servlet:
    multipart:
      #单个文件最大上传大小
      max-file-size: 10MB
      #每次请求上传文件大小最大值
      max-request-size: 30MB



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.zcbigdata.mybits_demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

